services:
  postgres-db:
    image: postgres:alpine
    container_name: formwise-db
    restart: unless-stopped
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'formwisedb'
      POSTGRES_USER: 'pguser'
      POSTGRES_PASSWORD: 'pgpassword'
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    volumes:
      - formwise-db:/var/lib/postgresql/data

volumes:
  formwise-db:
